kind: ConfigMap
apiVersion: v1
metadata:
  name: laravel-env
  namespace: laravel
data:
  .env: |
    APP_NAME=Laravel
    APP_ENV=local
    APP_KEY=base64:s1PnFQSaLHrWjv17UmSN8LdbhS9gQjxjbyZ94ZGSoec=
    APP_DEBUG=true
    APP_URL=http://localhost

    LOG_CHANNEL=stack

    DB_CONNECTION=mysql
    DB_HOST=laravel-mariadb.laravel
    DB_PORT=3306
    DB_DATABASE=laravel
    DB_USERNAME=root
    DB_PASSWORD=laravel

    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    #REDIS_HOST=127.0.0.1
    #REDIS_PASSWORD=null
    #REDIS_PORT=6379

    #MAIL_DRIVER=smtp
    #MAIL_HOST=smtp.mailtrap.io
    #MAIL_PORT=2525
    #MAIL_USERNAME=null
    #MAIL_PASSWORD=null
    #MAIL_ENCRYPTION=null

    #AWS_ACCESS_KEY_ID=
    #AWS_SECRET_ACCESS_KEY=
    #AWS_DEFAULT_REGION=us-east-1
    #AWS_BUCKET=

    #PUSHER_APP_ID=
    #PUSHER_APP_KEY=
    #PUSHER_APP_SECRET=
    #PUSHER_APP_CLUSTER=mt1

    #MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    #MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: laravel
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # Set nginx to serve files from the shared volume!
        root /var/www/html/public;
        server_name _;

        index index.php;

        location / {
          include  /etc/nginx/mime.types;
          try_files $uri /index.php?$query_string;
        }

        location = /favicon.ico { log_not_found off; access_log off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        sendfile off;

        client_max_body_size 100m;

        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_index index.php;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }
