apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-pv-public
  namespace: laravel
spec:
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: YourNfsAddress
    path: PathInYourNfsServer/public
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-pv-logs
  namespace: laravel
spec:
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: YourNfsAddress
    path: PathInYourNfsServer/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-pvc-public
  namespace: laravel
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: laravel-pv-public
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-pvc-logs
  namespace: laravel
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: laravel-pv-logs